SELECT 
    o.order_uid, 
    o.track_number, 
    o.entr AS entry, 
    d.name AS delivery_name, 
    d.phone AS delivery_phone, 
    d.zip AS delivery_zip, 
    d.city AS delivery_city, 
    d.address AS delivery_address, 
    d.region AS delivery_region, 
    d.email AS delivery_email, 
    p.t_action AS payment_transaction, 
    p.request_id AS payment_request_id, 
    p.currency AS payment_currency, 
    p.provider AS payment_provider, 
    p.amount AS payment_amount, 
    p.payment_dt AS payment_date, 
    p.bank AS payment_bank, 
    p.delivery_cost, 
    p.goods_total, 
    p.custom_fee, 
    i.chrt_id AS item_chrt_id, 
    i.price AS item_price, 
    i.rid AS item_rid, 
    i.name AS item_name, 
    i.sale AS item_sale, 
    i.size AS item_size, 
    i.total_price AS item_total_price, 
    i.nm_id AS item_nm_id, 
    i.brand AS item_brand, 
    i.status AS item_status, 
    o.locale, 
    o.internal_signature, 
    o.customer_id, 
    o.delivery_service, 
    o.shardkey, 
    o.sm_id, 
    o.date_created, 
    o.oof_shard
FROM orders o
INNER JOIN delivery d ON o.delivery_id = d.delivery_id
INNER JOIN payment p ON o.t_action = p.t_action
INNER JOIN items i ON o.track_number = i.track_number;